=== Fonsu/iap-final/src/main/resources/schemas/jobs-schema-output.json
{
      "$schema": "http://json-schema.org/draft-03/schema"
      , "properties": {
        "cod_oferta": {
          "description": "Offer id"
          , "maxLength": 4
          , "minLength": 2
          , "type": "string"
        }
        , "empresa": {
          "description": "Nombre de la empresa que ofrece el puesto"
          , "type": "string"
        }
        , "localidad": {
          "description": "Localidad de la oferta"
          , "type": "string"
        }
        , "jornada": {
          "description": "Tipo de jornada a realizar"
          , "type": "string"
        }
        , "duracion": {
          "description": "Duraci贸n oferta de trabajo"
          , "type": "string"
        }
        , "bolsa": {
          "description": "Duraci贸n oferta de trabajo"
          , "type": "string"
        }
        , "fecha_inicio": {
          "description": "Duraci贸n oferta de trabajo"
          , "type": "string"
        }
        , "num_plazas": {
          "description": "Duraci贸n oferta de trabajo"
          , "type": "string"
        }
      }
      , "type": "object"
      , "name": "Job"
    }

=== Fonsu/iap-final/target/classes/examples/jobs-post-example.json
{
            "cod_oferta": "1234"
            , "empresa": "EmpresaEjemplo"
            , "localidad": "Valencia"
            , "jornada": "flexible"
            , "duracion": "36 meses"
            , "bolsa": "300â‚¬"
            , "fecha_inicio": "31-01-2017"
            , "num_plazas": "20"
          }
